extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'
env:
  node: true
parser: '@typescript-eslint/parser'
plugins:
  - 'node'
  - '@typescript-eslint'
parserOptions:
  sourceType: module
rules:
  semi: off
  '@typescript-eslint/semi':
    - error
  '@typescript-eslint/no-use-before-define':
    - error
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/indent': off
  '@typescript-eslint/explicit-function-return-type':
    - error
    - allowExpressions: true
      allowTypedFunctionExpressions: true
      allowHigherOrderFunctions: true